title: Introduction to Mapbox
remote_theme: ubc-library-rc/rc-theme
  features: 
    - content.code.copy
    - content.code.annotate
color_scheme: rc
github_repo_url: "https://github.com/ubc-library-rc/intro-mapbox/" 

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown Extensions for highlighting sections of a code block (https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

